INSERT INTO phases (id, slug, name, description, typical_duration_days, validation_criteria, deliverables, kpis, order_index) VALUES
(1, 'application', 'Application', 'Collecter une candidature structurée et filtrer les projets sérieux.', 14, '["dossier complet","équipe identifiée","problème/solution clairs","deck ou one-pager"]', '["formulaire de candidature","profils fondateurs","pitch deck v1","lien produit/repo/démo"]', '["taux de complétion","temps moyen soumission","pièces manquantes","score initial"]', 1),
(2, 'initial-screening', 'Initial Screening', 'Premier tri rapide des candidatures.', 5, '["fit programme","qualité équipe","taille marché","faisabilité"]', '["fiche screening","note reviewer"]', '["taux acceptation/rejet","score moyen","temps review"]', 2),
(3, 'deep-review', 'Deep Review', 'Vérifier la crédibilité du projet.', 7, '["cohérence métriques","qualité produit","signaux marché","risques"]', '["data room minimale","accès produit","KPI sheet"]', '["complétude","red flags","score confiance"]', 3),
(4, 'interview', 'Interview', 'Évaluer l''équipe en direct.', 3, '["clarté vision","coachability","vitesse exécution","capacité commerciale"]', '["notes interview","scorecard"]', '["score moyen","accord reviewers","no-show"]', 4),
(5, 'committee-decision', 'Committee Decision', 'Décider de l''admission.', 4, '["score global","quorum","vote comité"]', '["decision memo","log votes","dossier admission"]', '["taux conversion","temps décision","unanimité"]', 5),
(6, 'onboarding', 'Onboarding', 'Intégrer le projet dans le programme.', 10, '["signature","accès outils","objectifs validés"]', '["onboarding checklist","accès outils","roadmap initiale"]', '["temps onboarding","complétion","satisfaction"]', 6),
(7, 'goal-setting', 'Goal Setting / OKRs', 'Définir des objectifs clairs.', 7, '["objectifs mesurables","alignement mentor"]', '["OKRs","roadmap"]', '["qualité OKRs","validation mentor"]', 7),
(8, 'product-validation', 'Product Validation', 'Valider le problème et la solution.', 21, '["feedback utilisateurs","tests terrain"]', '["interviews clients","prototype testé"]', '["nb interviews","taux validation"]', 8),
(9, 'mvp-iteration', 'MVP Iteration', 'Construire/améliorer le MVP.', 28, '["fonctionnalité opérationnelle"]', '["MVP fonctionnel","roadmap technique"]', '["vitesse dev","commits/semaine"]', 9),
(10, 'user-acquisition', 'User Acquisition', 'Tester acquisition utilisateurs.', 21, '["premiers utilisateurs"]', '["campagnes tests","funnel acquisition"]', '["CAC","conversion rate"]', 10),
(11, 'traction-validation', 'Traction Validation', 'Prouver l''intérêt du marché.', 30, '["croissance utilisateurs/revenus"]', '["KPI traction"]', '["croissance hebdo","rétention"]', 11),
(12, 'business-model', 'Business Model', 'Optimiser la monétisation.', 21, '["modèle viable"]', '["pricing","unit economics"]', '["LTV","marge","conversion"]', 12),
(13, 'metrics-tracking', 'Metrics Tracking', 'Structurer les KPIs.', 10, '["tracking en place"]', '["dashboard KPI"]', '["fiabilité données","fréquence MAJ"]', 13),
(14, 'weekly-reporting', 'Weekly Reporting', 'Suivi régulier.', 999, '["reporting complet"]', '["rapport hebdomadaire"]', '["régularité","qualité"]', 14),
(15, 'mentor-assignment', 'Mentor Assignment', 'Assigner mentors adaptés.', 7, '["matching expertise"]', '["assignation mentors"]', '["satisfaction","matching réussi"]', 15),
(16, 'mentor-sessions', 'Mentor Sessions', 'Accompagnement actif.', 999, '["sessions régulières"]', '["notes sessions"]', '["nb sessions","impact perçu"]', 16),
(17, 'milestone-tracking', 'Milestone Tracking', 'Suivre progression.', 999, '["milestones atteints"]', '["roadmap MAJ"]', '["milestone completion rate"]', 17),
(18, 'performance-review', 'Performance Review', 'Évaluer progression mi-programme.', 7, '["KPIs","execution"]', '["rapport intermédiaire"]', '["score progression"]', 18),
(19, 'growth-acceleration', 'Growth Acceleration', 'Accélérer croissance.', 30, '["scaling"]', '["stratégie croissance"]', '["croissance users","revenus"]', 19),
(20, 'fundraising-prep', 'Fundraising Prep', 'Préparer levée.', 21, '["readiness investisseurs"]', '["materials fundraising"]', '["readiness score"]', 20),
(21, 'pitch-deck', 'Pitch Deck Refinement', 'Améliorer pitch.', 10, '["clarté narrative"]', '["deck final"]', '["score pitch"]', 21),
(22, 'financial-model', 'Financial Model', 'Solidifier finances.', 10, '["cohérence projections"]', '["financial model"]', '["précision projections"]', 22),
(23, 'data-room', 'Data Room', 'Préparer investisseurs.', 10, '["documents complets"]', '["data room"]', '["complétude"]', 23),
(24, 'investor-outreach', 'Investor Outreach', 'Contacter investisseurs.', 28, '["meetings obtenus"]', '["liste investisseurs","emails"]', '["taux réponse","meetings"]', 24),
(25, 'demo-day-prep', 'Demo Day Prep', 'Préparer présentation finale.', 17, '["pitch prêt"]', '["pitch final","répétitions"]', '["readiness score"]', 25),
(26, 'demo-day', 'Demo Day', 'Présenter aux investisseurs.', 1, '["performance pitch"]', '["présentation live"]', '["feedback investisseurs"]', 26),
(27, 'graduation', 'Graduation', 'Sortie programme.', 1, '["programme complété"]', '["rapport final"]', '["taux graduation"]', 27),
(28, 'alumni-tracking', 'Alumni Tracking', 'Suivi long terme.', 999, '["activité post-programme"]', '["profil alumni"]', '["funding","croissance","survie"]', 28)
ON CONFLICT (id) DO NOTHING;
